name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'
      
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock', '.github/workflows/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Install Poetry
        run: |
          pip install poetry==1.8.3
          poetry config virtualenvs.in-project true
      
      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes
      
      - name: Install dependencies
        run: poetry install --with lint
      
      - name: Run ruff linting
        run: poetry run ruff check

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'
      
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock', '.github/workflows/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Install Poetry
        run: |
          pip install poetry==1.8.3
          poetry config virtualenvs.in-project true
      
      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes
      
      - name: Install dependencies
        run: poetry install --with test
      
      - name: Run pytest
        run: poetry run pytest
